### PR TITLE
chore(deps): update to function-sdk-go:v0.3.0

### PR DESCRIPTION
**Pull request by jbw976**
### Description of your changes

This PR bumps this template repo up to the latest release of function-sdk-go:v0.3.0.

Release notes: https://github.com/crossplane/function-sdk-go/releases/tag/v0.3.0

Closes #80
Closes #72
Closes #71

I've tested this locally with the steps from the main [README.md](https://github.com/crossplane/function-template-go/blob/main/README.md), all of which succeeed:

```
go generate ./...
go test ./...
docker build . --tag=runtime
crossplane xpkg build -f package --embed-runtime-image=runtime
```

I'll also take this for a test spin through the [Write a Composition Function in Go](https://docs.crossplane.io/v1.17/guides/write-a-composition-function-in-go/) guide in the docs.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Added or updated unit tests for my change.

[contribution process]: https://git.io/fj2m9
[docs]: https://docs.crossplane.io/contribute/contribute

### CODE REVIEW

**Comment by jbw976** [comment]
Ah, looks like Renovate was trying to do something similar with #80, but since this requires some manual updates to the xfn v1 types, I'll go ahead and set this PR to close that one (and a few others). Thank you though Renovate!

Looks like errors for building now though, I think because of the go version bump without also bumping the CI workflow files. I'll look into that too.

**Comment by jbw976** [comment]
Sweet, all checks (linting/building/etc.) are passing green now! 🟢

**Review by blakeromano — APPROVED** [review]
This LGTM...

Although we should make a follow up issue once this is fixed in Crossplane Core https://github.com/crossplane/crossplane/issues/5971 to update the package metadata api version.

**Comment by jbw976** [comment]
Docs update PR to update the go function guide as well: https://github.com/crossplane/docs/pull/814

**Comment by jbw976** [comment]
> Although we should make a follow up issue once this is fixed in Crossplane Core https://github.com/crossplane/crossplane/issues/5971 to update the package metadata api version.

Good call @blakeromano, thanks for taking a look and thanks for that reminder! I've opened #82 to track that bump 👍

**Review by phisco — APPROVED** [review]
Thanks @jbw976 and @blakeromano  🙏

**Pull request merged**
